import { useEffect, useState } from 'react'
import api, {exportApi} from '@/api/auth'
import { useAuth } from '@/store/AuthContext'
import { Button } from '@/components/ui/button'
import { Table,TableBody,TableCell,TableHead,TableHeader,TableRow } from '@/components/ui/table'
type Job={id:string;status:string;export_type:string;row_count:number;file_size:number|null;expires_at:string|null;queue_position:number|null;error_code:string|null}
const states:Record<string,string>={queued:'排队中',running:'生成中',succeeded:'可下载',failed:'失败',cancelled:'已取消',expired:'已过期'}
const errors:Record<string,string>={permission_changed:'资料权限已变动，请重新导出',interrupted:'服务重启中断，请重新提交',row_limit_exceeded:'行数超过上限，请缩小筛选范围',budget_exceeded:'生成超时，请缩小范围',disk_space_low:'磁盘可用空间不足',generation_failed:'生成失败，请提供请求编号',wal_budget_exceeded:'数据读取预算超限，请缩小范围',file_limit_exceeded:'文件超过大小上限',restored_without_artifact:'恢复备份后文件已失效，请重新提交'}
export default function ExportJobs(){
  const {user}=useAuth(),[items,setItems]=useState<Job[]>([]),[page,setPage]=useState(1),[total,setTotal]=useState(0),[manage,setManage]=useState(false),[refresh,setRefresh]=useState(0),[error,setError]=useState(''),[downloading,setDownloading]=useState<string|null>(null)
  useEffect(()=>{let stopped=false,timer:ReturnType<typeof setTimeout>;const load=async()=>{try{const r=await api.get('/export-jobs',{params:{page,manage}});if(stopped)return;setItems(r.data.items);setTotal(r.data.total);if(r.data.items.some((j:Job)=>['queued','running'].includes(j.status)))timer=setTimeout(load,document.hidden?15000:3000)}catch(e:any){if(!stopped)setError(e.response?.data?.detail||'无法读取任务')}};void load();return()=>{stopped=true;clearTimeout(timer)}},[page,manage,refresh])
  async function cancel(id:string){try{await api.post('/export-jobs/'+id+'/cancel');setRefresh(v=>v+1)}catch(e:any){setError(e.response?.data?.detail||'取消失败')}}
  async function sensitive(){const purpose=window.prompt('敏感资料将包含全部可导出客户的银行全号与联系人，请填写使用用途');if(!purpose?.trim())return;if(!window.confirm('确认按当前权限导出全部已核验的敏感开票资料？'))return;try{await exportApi.submit({export_type:'billing_sensitive',purpose,confirm_sensitive:true});setRefresh(v=>v+1)}catch(e:any){setError(e.response?.data?.detail||'提交失败')}}
  async function download(job:Job){setDownloading(job.id);setError('');try{const r=await api.get('/export-jobs/'+job.id+'/download',{responseType:'blob'});const url=URL.createObjectURL(r.data),link=document.createElement('a');link.href=url;link.download=`${job.export_type}_${job.id.slice(0,8)}.xlsx`;link.click();setTimeout(()=>URL.revokeObjectURL(url),1000)}catch(e:any){let message=e.response?.data?.detail;if(e.response?.data instanceof Blob){try{message=JSON.parse(await e.response.data.text()).detail?.message}catch{}}setError(message||'下载失败，请稍后重试')}finally{setDownloading(null)}}
  return <div className="space-y-4"><div className="flex flex-wrap justify-between gap-3"><h1 className="text-2xl font-semibold">导出任务</h1><div className="flex gap-2">{user?.permissions.includes('identity.manage')&&<Button variant="outline" onClick={()=>{setManage(!manage);setPage(1)}}>{manage?'我的任务':'管理队列'}</Button>}<Button variant="outline" onClick={()=>setRefresh(v=>v+1)}>刷新</Button></div></div>
    <p className="text-sm text-muted-foreground">关闭页面后任务继续生成。文件保留24小时，每次下载重新核对资料权限；已有下载时请稍后重试。</p>{user?.permissions.includes('billing.export_sensitive')&&<Button variant="outline" onClick={sensitive}>敏感开票资料批量导出</Button>}{error&&<p role="alert" className="text-destructive">{error}</p>}
    <div className="overflow-x-auto rounded border"><Table className="min-w-[760px]"><TableHeader><TableRow>{['任务','状态','已处理行数','文件与有效期','操作'].map(v=><TableHead key={v}>{v}</TableHead>)}</TableRow></TableHeader><TableBody>{items.map(job=><TableRow key={job.id}><TableCell>{({projects:'项目',signers:'签字人',billing_sensitive:'敏感开票资料'} as Record<string,string>)[job.export_type]}<br/><span className="text-xs font-mono">{job.id.slice(0,8)}</span></TableCell><TableCell>{states[job.status]}{job.queue_position&&` · 队列第${job.queue_position}项`}{job.error_code&&<p className="text-xs text-destructive">{errors[job.error_code]||'任务失败，请提供任务编号'}</p>}</TableCell><TableCell>{job.row_count}</TableCell><TableCell>{job.file_size?`${(job.file_size/1024).toFixed(1)} KiB · 下载约${Math.max(1,Math.ceil(job.file_size/102400))}秒`: '-'}{job.expires_at&&<p className="text-xs">有效至 {new Date(job.expires_at+'Z').toLocaleString('zh-CN',{timeZone:'Asia/Shanghai'})}</p>}</TableCell><TableCell>{['queued','running'].includes(job.status)&&<Button variant="outline" onClick={()=>cancel(job.id)}>取消</Button>}{job.status==='succeeded'&&<Button disabled={downloading!==null} onClick={()=>download(job)}>{downloading===job.id?'下载中…':'下载'}</Button>}</TableCell></TableRow>)}</TableBody></Table></div>
    {items.length===0&&<p>暂无导出任务。可从项目列表按筛选提交导出。</p>}<div className="flex gap-2 items-center"><Button variant="outline" disabled={page===1} onClick={()=>setPage(page-1)}>上一页</Button><span>共{total}项</span><Button variant="outline" disabled={page*20>=total} onClick={()=>setPage(page+1)}>下一页</Button></div></div>
}
