import { useEffect,useState } from 'react'
import api, {downloadFile} from '@/api/auth'
import { Button } from '@/components/ui/button'
import { Input } from '@/components/ui/input'
import { Label } from '@/components/ui/label'
type Rule={id:number;name:string;template:string;current_sequence:number}
export default function SystemBackup(){
  const [password,setPassword]=useState(''),[confirmation,setConfirmation]=useState(''),[busy,setBusy]=useState(false),[message,setMessage]=useState(''),[hold,setHold]=useState(false),[rules,setRules]=useState<Rule[]>([]),[values,setValues]=useState<Record<number,string>>({}),[reason,setReason]=useState(''),[checked,setChecked]=useState(false)
  async function load(){try{const r=await api.get('/system/backup/reconciliation');setHold(r.data.required);setRules(r.data.rules)}catch(e:any){setMessage(e.userMessage || e.response?.data?.detail||'无法读取恢复状态')}}
  useEffect(()=>{void load()},[])
  async function backup(event:React.FormEvent){event.preventDefault();if(password!==confirmation){setMessage('两次密码不一致');return}setBusy(true);setMessage('');try{const blob=await downloadFile('/system/backup','POST',{password});const url=URL.createObjectURL(blob),link=document.createElement('a');link.href=url;link.download=`业码汇加密备份_${new Date().toISOString().slice(0,10)}.ymhb`;link.click();setTimeout(()=>URL.revokeObjectURL(url),1000);setPassword('');setConfirmation('');setMessage('加密备份已提供下载，请保管文件及密码')}catch(e:any){setMessage(e.userMessage || '备份失败，请联系管理员')}finally{setBusy(false)}}
  async function reconcile(event:React.FormEvent){event.preventDefault();setBusy(true);try{const r=await api.post('/system/backup/reconcile',{rules:rules.map(rule=>({id:rule.id,actual_last_sequence:Number(values[rule.id])})),reason,confirmed_external_records:checked});setMessage(r.data.message);await load()}catch(e:any){setMessage(e.userMessage || e.response?.data?.detail||'核号失败')}finally{setBusy(false)}}
  return <div className="space-y-5"><h1 className="text-2xl font-semibold">备份与恢复</h1><p className="text-sm text-muted-foreground">备份含一致性业务数据、开票解密密钥与设备身份。请存放到本机之外的受控位置，单独保管密码。恢复使用相同版本的完整安装包，并选择全新空数据目录。</p>
    <form className="max-w-lg space-y-3" onSubmit={backup}><Label htmlFor="backup-password">备份密码（至少12位）</Label><Input id="backup-password" type="password" autoComplete="new-password" minLength={12} maxLength={128} value={password} onChange={e=>setPassword(e.target.value)} required/><Label htmlFor="backup-confirm">确认密码</Label><Input id="backup-confirm" type="password" autoComplete="new-password" value={confirmation} onChange={e=>setConfirmation(e.target.value)} required/><Button disabled={busy}>{busy?'正在处理…':'生成并下载加密备份'}</Button></form>
    {message&&<p role="status">{message}</p>}{hold&&<form className="space-y-3" onSubmit={reconcile}><h2 className="text-lg font-semibold">恢复后编号核对</h2><p className="text-sm text-destructive">业务写入暂时关闭。请核对备份之后实际已交付的报告编号，填写每条规则的已交付最大序号。核号不会补回备份之后丢失的业务资料。</p>{rules.map(rule=><div key={rule.id} className="max-w-xl space-y-1"><Label htmlFor={'sequence-'+rule.id}>{rule.name} · {rule.template}（备份序号{rule.current_sequence}）</Label><Input id={'sequence-'+rule.id} type="number" min={rule.current_sequence} max={1000000000} required value={values[rule.id]??''} onChange={e=>setValues({...values,[rule.id]:e.target.value})}/></div>)}<Input aria-label="核对依据与原因" placeholder="填写核对依据与原因" required maxLength={500} value={reason} onChange={e=>setReason(e.target.value)}/><label className="flex items-center gap-2"><input type="checkbox" checked={checked} onChange={e=>setChecked(e.target.checked)} required/>已核对外部实际交付记录</label><Button disabled={busy}>记录核号并恢复写入</Button></form>}
  </div>
}
